### ISSUE TITLE
asExecute return value does not work as expected

### ISSUE THREAD

**Issue by vladimirkroupa** [seratch/kotliquery#33]
In README, there is an [example](https://github.com/seratch/kotliquery#user-content-ddl-execution) showing how to run a DDL query. I would expect that the boolean value returned in the example to represent a success/failure of the DDL query execution.

But the boolean value returned from _ExecuteQueryAction_ is in fact the return value of [_execute_](https://docs.oracle.com/javase/7/docs/api/java/sql/PreparedStatement.html#execute()) method from _PreparedStatemement_. The documentation for this method says:

> Returns:
    true if the first result is a ResultSet object; false if the first result is an update count or there is no result

This means that the return value of running an ExecuteQueryAction is useless as neither the update count or ResultSet can be accessed.

**Comment by seratch** [comment]
It’s the JDBC spec. I understand it if you’re saying that the spec is not understandable or not useful. In general, if a failure happens during the execution, an exception will be thrown.

I don’t have any plans to change the API. But, if you have other idea to address/mitigate your concern, I would like to know more about it. Otherwise, I don’t have any actions to take for now. In that case, I would appreciate it if you could close this issue this time.

**Comment by seratch** [comment]
Thank you for your understanding.
